export const mockChambres = [
  { id: "chambre-1", numero: 'A-101', capacite: 2, statut: 'occupée', occupants: [1, 2] },
  { id: 2, numero: '102', capacite: 1, statut: 'libre', occupants: [] },
  { id: 3, numero: '103', capacite: 2, statut: 'occupée', occupants: [3] },
  { id: 4, numero: '104', capacite: 1, statut: 'occupée', occupants: [4] },
  { id: 5, numero: '201', capacite: 2, statut: 'libre', occupants: [] },
  { id: 6, numero: '202', capacite: 2, statut: 'occupée', occupants: [5, 6] },
];

export const mockEtudiants = [
  { id: 1, nom: 'Martin Dupont', chambre: '101', telephone: '0601020304', email: 'martin@email.com', dateArrivee: '2023-09-01' },
  { id: 2, nom: 'Sophie Laurent', chambre: '101', telephone: '0602030405', email: 'sophie@email.com', dateArrivee: '2023-09-01' },
  { id: 3, nom: 'Thomas Bernard', chambre: '103', telephone: '0603040506', email: 'thomas@email.com', dateArrivee: '2023-10-15' },
  { id: 5, nom: 'Camille Moreau', chambre: '202', telephone: '0605060708', email: 'camille@email.com', dateArrivee: '2024-01-10' },
];

export const mockStagiaires = [
  { 
    id: 4, 
    nom: 'Mahdi Nasri', 
    firstName: 'Mahdi',
    lastName: 'Nasri',
    chambre: '104', 
    telephone: '44772168', 
    email: 'mahdi@email.com', 
    dateArrivee: '2024-01-05', 
    dateDepart: '2024-06-30', 
    entreprise: 'ZetaBox',
    type: 'interne',  // Indique que c'est un stagiaire interne
    avatar: null,
    dateOfBirth: '1996-05-15',
    placeOfBirth: 'Tunis',
    nationality: 'Tunisienne',
    currentSituation: 'Étudiant',
    cinNumber: 'TU12345678',
    cinPlace: 'Tunis',
    cinDate: '2015-03-20',
    phoneNumber: '44772168',
    sendingAddress: '25 Rue des Oliviers',
    city: 'Tunis',
    postalCode: '1002',
    centerName: 'Institut Supérieur d\'Informatique',
    specialization: 'Développement Web',
    cycle: 'Master',
    fatherFirstName: 'Ahmed',
    fatherLastName: 'Nasri',
    fatherPhone: '22334455',
    fatherJob: 'Ingénieur',
    fatherJobPlace: 'Entreprise ABC',
    motherFirstName: 'Fatima',
    motherLastName: 'Nasri',
    motherPhone: '66778899',
    motherJob: 'Enseignante',
    motherJobPlace: 'École XYZ',
    numberOfBrothers: 1,
    numberOfSisters: 2,
    hobby: 'Programmation, Football',
    trainingPeriodFrom: '2024-01-05',
    trainingPeriodTo: '2024-06-30'
  },
  { 
    id: 6, 
    nom: 'Amira Ben Abdallah', 
    firstName: 'Amira',
    lastName: 'Ben Abdallah',
    chambre: '202', 
    telephone: '55667788', 
    email: 'amira@email.com', 
    dateArrivee: '2024-02-01', 
    dateDepart: '2024-07-31', 
    entreprise: 'ZetaBox',
    type: 'externe',  // Indique que c'est une stagiaire externe
    avatar: null,
    cinNumber: 'TU87654321',
    dateOfBirth: '1997-08-23',
    placeOfBirth: 'Sousse',
    assignedCenter: 'Centre de Formation Technique',
    specialization: 'Design Graphique',
    groupNumber: 'G7',
    trainingPeriodFrom: '2024-02-01',
    trainingPeriodTo: '2024-07-31'
  },
  { 
    id: 7, 
    nom: 'Karim Mejri', 
    firstName: 'Karim',
    lastName: 'Mejri',
    chambre: '105', 
    telephone: '99887766', 
    email: 'karim@email.com', 
    dateArrivee: '2024-03-10', 
    dateDepart: '2024-09-10', 
    entreprise: 'Technowave',
    type: 'interne',
    avatar: null,
    dateOfBirth: '1995-11-02',
    placeOfBirth: 'Sfax',
    nationality: 'Tunisienne',
    currentSituation: 'Étudiant',
    cinNumber: 'TU45678901',
    cinPlace: 'Sfax',
    cinDate: '2016-07-15',
    phoneNumber: '99887766',
    sendingAddress: '8 Rue de la Liberté',
    city: 'Sfax',
    postalCode: '3000',
    centerName: 'École Nationale d\'Ingénieurs',
    specialization: 'Génie Logiciel',
    cycle: 'Licence',
    fatherFirstName: 'Mohamed',
    fatherLastName: 'Mejri',
    fatherPhone: '33445566',
    fatherJob: 'Commerçant',
    fatherJobPlace: 'Marché Central',
    motherFirstName: 'Aisha',
    motherLastName: 'Mejri',
    motherPhone: '77889900',
    motherJob: 'Médecin',
    motherJobPlace: 'Hôpital Régional',
    numberOfBrothers: 2,
    numberOfSisters: 1,
    hobby: 'Natation, Lecture',
    trainingPeriodFrom: '2024-03-10',
    trainingPeriodTo: '2024-09-10'
  },
  {
    id: 8,
    nom: 'Sarra Triki',
    firstName: 'Sarra',
    lastName: 'Triki',
    chambre: null,
    telephone: '22113344',
    email: 'sarra@email.com',
    dateArrivee: '2024-01-15',
    dateDepart: '2024-05-15',
    entreprise: 'DigiTech',
    type: 'externe',
    avatar: null,
    cinNumber: 'TU98765432',
    dateOfBirth: '1998-04-12',
    placeOfBirth: 'Monastir',
    assignedCenter: 'Institut Supérieur des Sciences Appliquées',
    specialization: 'Marketing Digital',
    groupNumber: 'G3',
    trainingPeriodFrom: '2024-01-15',
    trainingPeriodTo: '2024-05-15'
  }
];

export const mockTachesCuisine = [
  { id: 1, date: '2025-05-13', creneau: 'Matin', responsable: 1, tache: 'Préparation petit-déjeuner' },
  { id: 2, date: '2025-05-13', creneau: 'Soir', responsable: 2, tache: 'Nettoyage cuisine' },
  { id: 3, date: '2025-05-14', creneau: 'Matin', responsable: 3, tache: 'Préparation petit-déjeuner' },
  { id: 4, date: '2025-05-14', creneau: 'Soir', responsable: 4, tache: 'Nettoyage cuisine' },
  { id: 5, date: '2025-05-15', creneau: 'Matin', responsable: 5, tache: 'Préparation petit-déjeuner' },
  { id: 6, date: '2025-05-15', creneau: 'Soir', responsable: 6, tache: 'Nettoyage cuisine' },
];

export const mockKitchenTasks = [
  {
    id: '1',
    type: 'nettoyage',
    description: 'Nettoyer le sol de la cuisine',
    date: '2025-05-12',
    timeSlot: '10:00 - 12:00',
    assignedTo: '101',
    assignedToName: 'Thomas Martin',
    status: 'en attente'
  },
  {
    id: '2',
    type: 'préparation',
    description: 'Préparer les légumes pour le dîner',
    date: '2025-05-12',
    timeSlot: '16:00 - 18:00',
    assignedTo: '102',
    assignedToName: 'Emma Bernard',
    status: 'en attente'
  },
  {
    id: '3',
    type: 'service',
    description: 'Servir le dîner',
    date: '2025-05-12',
    timeSlot: '18:00 - 20:00',
    assignedTo: '103',
    assignedToName: 'Lucas Dubois',
    status: 'en attente'
  },
  {
    id: '4',
    type: 'vaisselle',
    description: 'Faire la vaisselle du dîner',
    date: '2025-05-12',
    timeSlot: '20:00 - 22:00',
    assignedTo: '104',
    assignedToName: 'Sofia Petit',
    status: 'en attente'
  },
  {
    id: '5',
    type: 'nettoyage',
    description: 'Nettoyer les réfrigérateurs',
    date: '2025-05-13',
    timeSlot: '14:00 - 16:00',
    assignedTo: '',
    assignedToName: '',
    status: 'en attente'
  },
  {
    id: '6',
    type: 'rangement',
    description: 'Ranger les provisions reçues',
    date: '2025-05-13',
    timeSlot: '10:00 - 12:00',
    assignedTo: '105',
    assignedToName: 'Léo Richard',
    status: 'en attente'
  },
  {
    id: '7',
    type: 'préparation',
    description: 'Préparer les entrées du déjeuner',
    date: '2025-05-14',
    timeSlot: '08:00 - 10:00',
    assignedTo: '106',
    assignedToName: 'Camille Robert',
    status: 'en attente'
  },
  {
    id: '8',
    type: 'nettoyage',
    description: 'Nettoyer les plans de travail',
    date: '2025-05-14',
    timeSlot: '12:00 - 14:00',
    assignedTo: '107',
    assignedToName: 'Noah Simon',
    status: 'en attente'
  },
  {
    id: '9',
    type: 'service',
    description: 'Servir le petit déjeuner',
    date: '2025-05-15',
    timeSlot: '08:00 - 10:00',
    assignedTo: '108',
    assignedToName: 'Jade Leroy',
    status: 'en attente'
  },
  {
    id: '10',
    type: 'vaisselle',
    description: 'Faire la vaisselle du petit déjeuner',
    date: '2025-05-15',
    timeSlot: '10:00 - 12:00',
    assignedTo: '',
    assignedToName: '',
    status: 'en attente'
  },
  // Add more tasks as needed
];
